apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  containers:
  - name: python-container
    image: python:3.9-slim
    command: ["python", "-c", "while True: pass"]

