apiVersion: v1
kind: Service
metadata:
  name: venkatesh-backend-svc-test
spec:
  selector:
    app: venkatesh-backend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
  type: ClusterIP
