apiVersion: apps/v1
kind: Deployment
metadata:
  name: venkatesh-frontend-raw-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venkatesh-frontend-raw
  template:
    metadata:
      labels:
        app: venkatesh-frontend-raw
    spec:
      containers:
      - name: venkatesh-frontend-raw
        image: venkateshkvrs/hello-app-frontend-raw 
        ports:
        - containerPort: 3000
