version: '3.8'

services:
  backend:
    build: ./backend/Python
    container_name: backend-docker-app
    ports:
      - "5000:5000"
    depends_on:
      mysql-container:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://mysql-container:3306 || exit 1"]
      interval: 60s
      retries: 10
      timeout: 5s

  frontend:
    build: ./frontend
    container_name: frontend-docker-app
    ports:
      - "3000:3000"

  mysql-container:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 60s
      retries: 10
      timeout: 5s

# version: '3.8'

# services:
#   backend:
#     build: ./backend/Python
#     container_name: backend-docker-app
#     ports:
#       - "5000:5000"

#   frontend:
#     build: ./frontend
#     container_name: frontend-docker-app
#     ports:
#       - "3000:3000"

# networks:
#   hello-network:
#     driver: bridge